openapi: "3.0.0"
info:
  version: 1.0.0
  title: Minimal ping API server
paths:
  /ping/{user_id}:
    get:
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          description: User ID for greeting
      responses:
        '200':
          description: ping response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PingResponse'
components:
  schemas:
    PingResponse:
      type: object
      required:
        - message
        - user_id
      properties:
        message:
          type: string
          example: "Hello, user123!"
        user_id:
          type: string
          example: "user123"